- hosts: all
  remote_user: root
  tasks:
    - name: Define vars
      set_fact:
        project_name: myapp
        github_repo: pprishchepa/deploy-app-example
        github_user: "{{ lookup('env', 'GITHUB_USERNAME') }}"
        github_token: "{{ lookup('env', 'GITHUB_ACCESS_TOKEN') }}"

    - name: Define vars
      set_fact:
        project_app: "/opt/server/apps/{{ project_name }}"
        project_data: "/opt/server/data/{{ project_name }}"
        project_backups: "/opt/server/backups/{{ project_name }}"

    - name: Create app dir
      ansible.builtin.file:
        path: "{{ project_app }}"
        state: directory
        mode: '0755'

    - name: Create data dir
      ansible.builtin.file:
        path: "{{ project_data }}"
        state: directory
        mode: '0755'

    - name: Create backups dir
      ansible.builtin.file:
        path: "{{ project_backups }}"
        state: directory
        mode: '0755'

    - name: Checkout codebase
      ansible.builtin.git:
        repo: "https://{{ github_user }}:{{ github_token }}@github.com/{{ github_repo }}.git"
        dest: "{{ project_app }}"
        version: "{{ lookup('vars', 'commit-sha1', default='HEAD') }}"
        force: yes
      environment:
        GIT_TERMINAL_PROMPT: 0
      register: checkout_result
    - debug: "msg='Current SHA-1 is {{ checkout_result.after }} (prev. {{ checkout_result.before }})'"

    - name: Update .env file
      shell: |
        echo "PROJECT_ENV=production" > {{ project_app }}/.env
        echo "PROJECT_NAME={{ project_name }}" >> {{ project_app }}/.env
        echo "PROJECT_DATA={{ project_data }}" >> {{ project_app }}/.env

    - name: Init docker-compose.yml
      ansible.builtin.copy:
        remote_src: true
        src: "{{ project_app }}/docker-compose.production.yml.dist"
        dest: "{{ project_app }}/docker-compose.yml"
        mode: "0644"

    - name: Upload myapp bin
      copy:
        src: ../build/myapp
        dest: "{{ project_app }}/build"
        mode: 0755

    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: "{{ project_app }}"
        build: yes
        remove_orphans: yes